# Generated by Django 2.2.12 on 2020-05-28 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('djangocms_table', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table',
            new_name='TableModel'
        ),
    ]
