# Generated by Django 2.2.12 on 2020-05-28 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_table', '0002_auto_20200528_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablemodel',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_table_tablemodel', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
