# Generated by Django 2.2.12 on 2020-05-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_table', '0004_auto_20200528_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablemodel',
            name='footer_rows',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Footer'),
        ),
        migrations.AlterField(
            model_name='tablemodel',
            name='header_rows_left',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Left'),
        ),
        migrations.AlterField(
            model_name='tablemodel',
            name='header_rows_top',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Top'),
        ),
    ]
